# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileExam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileExam

   pod 'IHProgressHUD'
   pod 'Starscream', '~> 3.0.2'
   pod 'Alamofire'
   pod 'BRYXBanner'
   pod 'Crashlytics', '~> 3.10.9'
   pod 'SwifterSwift'

 

end
